export const data = [
  {
    question: "What does HTML stand for?",
    option1: "Hypertext Markup Language",
    option2: "Hyperlink and Text Markup Language",
    option3: "High-Level Text Markup Language",
    option4: "Home Tool Markup Language",
    ans: 1,
  },
  {
    question: "Which CSS property is used to change the text color of an element?",
    option1: "color",
    option2: "text-color",
    option3: "font-color",
    option4: "foreground-color",
    ans: 1,
  },
  {
    question: "In JavaScript, what is the 'typeof' operator used for?",
    option1: "Checking the type of a variable",
    option2: "Converting a variable to a specific type",
    option3: "Assigning a variable to a new type",
    option4: "Creating a new variable type",
    ans: 1,
  },
  {
    question: "Which HTML tag is used for creating an ordered list?",
    option1: "<ol>",
    option2: "<ul>",
    option3: "<li>",
    option4: "<list>",
    ans: 1,
  },
  {
    question: "What is the purpose of the 'box-sizing' property in CSS?",
    option1: "Defines the width of an element",
    option2: "Defines the height of an element",
    option3: "Defines how the total width and height of an element is calculated",
    option4: "Defines the border size of an element",
    ans: 3,
  },
  {
    question: "In JavaScript, what does the 'NaN' stand for?",
    option1: "Not a Number",
    option2: "No and Never",
    option3: "Null and None",
    option4: "Negative and Null",
    ans: 1,
  },
  {
    question: "Which HTML tag is used for embedding JavaScript code?",
    option1: "<js>",
    option2: "<script>",
    option3: "<javascript>",
    option4: "<code>",
    ans: 2,
  },
  {
    question: "What is the purpose of the 'margin' property in CSS?",
    option1: "Defines the space between elements",
    option2: "Defines the outer border of an element",
    option3: "Defines the inner padding of an element",
    option4: "Defines the width of an element",
    ans: 1,
  },
  {
    question: "What does the 'document.getElementById()' function return in JavaScript?",
    option1: "A class",
    option2: "An array",
    option3: "An HTML element",
    option4: "A string",
    ans: 3,
  },
  {
    question: "Which CSS property is used to make text bold?",
    option1: "font-weight",
    option2: "text-bold",
    option3: "bold",
    option4: "font-bold",
    ans: 1,
  },
  {
    question: "What is the purpose of the 'alt' attribute in the HTML 'img' tag?",
    option1: "Defines the image source",
    option2: "Specifies an alternative text for the image",
    option3: "Sets the image height",
    option4: "Defines the image alignment",
    ans: 2,
  },
  {
    question: "Which JavaScript method is used to add an element to the end of an array?",
    option1: "push()",
    option2: "add()",
    option3: "append()",
    option4: "addToEnd()",
    ans: 1,
  },
  {
    question: "In CSS, what is the 'float' property used for?",
    option1: "Positioning an element to the left or right",
    option2: "Making text float on the page",
    option3: "Clearing all floated elements",
    option4: "Adding shadow to an element",
    ans: 1,
  },
  {
    question: "What does the 'localStorage' object in JavaScript do?",
    option1: "Stores data with no expiration time",
    option2: "Stores data that expires after a session",
    option3: "Stores data with limited storage capacity",
    option4: "Stores data in server storage",
    ans: 1,
  },
  {
    question: "Which HTML tag is used for creating a hyperlink?",
    option1: "<link>",
    option2: "<href>",
    option3: "<a>",
    option4: "<hyperlink>",
    ans: 3,
  },
  {
    question: "In JavaScript, what is the purpose of the 'return' statement?",
    option1: "Exits a loop or a switch statement",
    option2: "Outputs a value from a function",
    option3: "Declares a variable",
    option4: "Jumps to a specific line of code",
    ans: 2,
  },
];
